---
title: "36-315 Static Graphics Project"
author: "Yeju Ahn"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

+  A link to the dataset:
[here](https://www.kaggle.com/uciml/restaurant-data-with-consumer-ratings)

*CSV FILE*
```{r,message=FALSE}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(d3heatmap)
library(plyr)
library(ggcorrplot)

restaurant <- read.csv("https://raw.githubusercontent.com/YejuAhn/315-Interactive_Graphics_Project/master/geoplaces2.csv")

rating_final <- read.csv("https://raw.githubusercontent.com/YejuAhn/315-Interactive_Graphics_Project/master/rating_final.csv")

user <- read.csv("https://raw.githubusercontent.com/YejuAhn/315-Interactive_Graphics_Project/master/userprofile.csv")

placeID_list <- unique(rating_final$placeID)
my_data_final <- data.frame()
for (i in 1:length(placeID_list)){
  curr.placeID <- placeID_list[i]
  curr.placeID.data <- rating_final[which(rating_final$placeID == curr.placeID),]
  curr.avg.rating <- mean(curr.placeID.data$rating)
  curr.avg.food_rating <- mean(curr.placeID.data$food_rating)
  curr.avg.service_rating <- round(median(curr.placeID.data$service_rating))
  curr.list <- data.frame(placeID = curr.placeID, rating = curr.avg.rating, food_rating =  curr.avg.food_rating, service_rating = curr.avg.service_rating)
  my_data_final <- rbind(my_data_final, curr.list)
}
total <- merge(restaurant,my_data_final,by="placeID")
my_data <- as_tibble(total)
my_data %>% select(placeID, price, city, rating, food_rating,service_rating)

total_user<- merge(user,rating_final,by="userID")
user_data <- as_tibble(total_user)

#for HEAT MAP
if (!require("gplots")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
if (!require("RColorBrewer")) {
   install.packages("RColorBrewer", dependencies = TRUE)
   library(RColorBrewer)
}

my_data %>% select(placeID, price, rating, food_rating,service_rating)

my_data$price <- mapvalues(my_data$price, from = c("low", "medium","high"), to = c("0", "1","2"))
my_data <- mutate(my_data, price = as.numeric(price), rating = round(floor(rating)))

final <- my_data %>% select(rating, price)
mat = as.matrix(final)
```
#HEATMAP
```{r,message=FALSE, fig.width = 9, fig.height = 10}
d3heatmap(mat, scale="column", colors="Spectral")
```

#USERProfile

```{r}
library(GGally)
user_data <- dplyr::select(user_data,drink_level,marital_status,rating, activity, religion,
                           dress_preference, smoker)

user_data <- mutate(user_data,
                    activity = as.numeric(activity),
                    religion = as.numeric(religion),
                    dress_preference = as.numeric(dress_preference),
                    smoker = as.numeric(dress_preference),
                    marital_status	 = as.numeric(marital_status),
                    drink_level	 = as.numeric(drink_level))

corr <- round(cor(user_data), 1)
head(corr[, 1:ncol(user_data)])

user_mat = as.matrix(user_data)

p.mat <- cor_pmat(user_data)
head(p.mat[, 1:4])
ggcorrplot(corr, hc.order = TRUE,
   outline.col = "white", 
   colors = c("#6D9EC1", "white", "#E46726"))

ggcorr(user_mat,  nbreaks = 5, palette = "RdGy", label = TRUE)
```






